server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cms
    username: root
    password: Nunarijal12#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


project:
  image: images/

#logging:
#  level:
#    org:
#      springframework:
#        security: INFO

# file size
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

